language: python
python:
  - "3.5"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda create -q -n cde python=3.5 pip
  - pip install -r requirements.txt
  - source activate cde
  - python setup.py install
  - cde data download
script:
  - import Cython
  - print(Cython.__version__)
  - pytest 
